### ISSUE TITLE
Implement MVC authorization

### ISSUE THREAD

**Issue by EdvardPotapenko** [krok-lives-matter/CaffeMenuBot_Back-End#8]
### Authentication example
https://github.com/vova-lantsov-dev/freelance/tree/master/RobokassaBot/RobokassaBot.AppHost

### Password hashing algorithm problem
Hashing algorithm provided [here](https://github.com/vova-lantsov-dev/freelance/blob/8c383c1472b5844098d3d677deb06a75d76a2b26/RobokassaBot/RobokassaBot.AppHost/Authentication/DatabaseBasedAuthService.cs#L64-L73) is wrong. You need to replace it with a valid one. For more information, contact @vova-lantsov-dev 

### Progress
- [x] Login POST endpoint
- [ ] Logout POST endpoint
- [ ] Unit tests for password hashing (comparing BASE64 values)
- [x] Login integration tests (happy day scenario; user not exists scenario; bad request data scenario - already completed by @vova-lantsov-dev)
- [ ] Logout integration tests

**Comment by dhurskyi** [comment]
Tomorrow there'll be more enhancements like processing authentication form :)
